require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0.3
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - gems/**/*
    - vendor/**/*
    - Gemfile

# Block has too many lines.
Metrics/BlockLength:
  Exclude:
    - spec/**/*

Rails:
  Enabled: true

# for Windows
Layout/EndOfLine:
  Enabled: false

# Prefer single-quoted strings when you don't need string interpolation or special symbols.
Style/StringLiterals:
  Enabled: false

# Line is too long.
#Layout/LineLength:
#  Enabled: false

# Missing frozen string literal comment.
Style/FrozenStringLiteralComment:
  Enabled: false

# Missing top-level documentation comment for module ApplicationHelper.
Style/Documentation:
  Enabled: false

# Do not use space inside array brackets.
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

# Do not use spaces inside percent literal delimiters.
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

# Put empty method definitions on a single line.
Style/EmptyMethod:
  Enabled: false
